import { ProductsModel } from './product.model';

export const myProducts: ProductsModel[] = [
  {
    name: 'Classical Guitar Model 001',
    category: 'Classical Guitar',
    price: 515,
    description: '',
    imageUrl: '../../assets/image/guitar/g-black.jpg',
    slider2: '../../assets/image/guitar/gblack2.jpg',
    slider3: '../../assets/image/guitar/gblack2.jpg',
  },
  {
    name: 'Electic Guitar Model 002',
    category: 'Electric Guitar',
    price: 515,
    description: '',
    imageUrl: '../../assets/image/guitar/g-red.jpg',
    slider2: '../../assets/image/guitar/gred2.jpg',
    slider3: '../../assets/image/guitar/gred3.jpg',
  },
  {
    name: 'Bass Guitar Model 003',
    category: 'Bass Guitar',
    price: 515,
    description: '',
    imageUrl: '../../assets/image/guitar/g-violet.jpg',
    slider2: '../../assets/image/guitar/gviolet2.jpg',
    slider3: '../../assets/image/guitar/gviolet3.jpg',
  },
  //{
  //   name: 'Cymbals1',
  //   category: 'Cymbals',
  //   price: 515,
  //   description: '',
  //   imageUrl: '../../assets/image/cymbals/c-black.jpg',
  //   slider2: '../../assets/image/cymbals/c-black2.jpg',
  //   slider3: '../../assets/image/cymbals/c-black3.jpg',
  // },
  // {
  //   name: 'Cymbals2',
  //   category: 'Cymbals',
  //   price: 515,
  //   description: '',
  //   imageUrl: '../../assets/image/cymbals/c-brown.jpg',
  //   slider2: '../../assets/image/cymbals/cbrown2.jpg',
  //   slider3: '../../assets/image/cymbals/cbrown3.jpg',
  // },
  // {
  //   name: 'Cymbals6',
  //   category: 'Cymbals',
  //   price: 515,
  //   description: '',
  //   imageUrl: '../../assets/image/cymbals/c-customize.jpg',
  //   slider2: '../../assets/image/cymbals/c-customize2.jpg',
  //   slider3: '../../assets/image/cymbals/c-customize3.jpg',
  // },
  // {
  //   name: 'Cymbals7',
  //   category: 'Cymbals',
  //   price: 515,
  //   description: '',
  //   imageUrl: '../../assets/image/cymbals/c-red.jpg',
  //   slider2: '../../assets/image/cymbals/c-red2.jpg',
  //   slider3: '../../assets/image/cymbals/c-red3.jpg',
  // },
  // {
  //   name: 'Snare2',
  //   category: 'Snare',
  //   price: 515,
  //   description: '',
  //   imageUrl: '../../assets/image/snare/snare1.jpg',
  //   slider2: '../../assets/image/snare/snare1.jpg',
  //   slider3: ' ',
  // },

  // {
  //   name: 'Keyboard2',
  //   category: 'Keyboard',
  //   price: 515,
  //   description: '',
  //   imageUrl: '../../assets/image/keyboards/k-black.jpg',
  //   slider2: '../../assets/image/keyboards/kblack2.jpg',
  //   slider3: ' ',
  // },
  // {
  //   name: 'Keyboard3',
  //   category: 'Keyboard',
  //   price: 515,
  //   description: '',
  //   imageUrl: '../../assets/image/keyboards/k-blue-army.jpg',
  //   slider2: '../../assets/image/keayboards/kbluearmy2.jpg',
  //   slider3: '',
  // },
  // {
  //   name: 'Keyboard4',
  //   category: 'Keyboard',
  //   price: 515,
  //   description: '',
  //   imageUrl: '../../assets/image/keyboards/k-stripes.jpg',
  //   slider2: '../../assets/image/keayboards/kstripes2.jpg',
  //   slider3: '',
  // },
  // {
  //   name: 'Snare',
  //   category: 'Snare',
  //   price: 515,
  //   description: '',
  //   imageUrl: '../../assets/image/snare/s-army.jpg',
  //   slider2: '../../assets/image/snare/s-army2.jpg',
  //   slider3: '../../assets/image/snare/s-army3.jpg',
  // },
  // {
  //   name: 'Keyboard1',
  //   category: 'Keyboard',
  //   price: 515,
  //   description: '',
  //   imageUrl: '../../assets/image/keyboards/k-black.jpg',
  //   slider2: '../../assets/image/keayboards/lblack2.jpg',
  //   slider3: '',
  // },
  {
    name: 'Ukulele',
    category: 'Ukulele',
    price: 515,
    description: '',
    imageUrl: '../../assets/image/ukulele/ukulele.jpg',
    slider2: '../../assets/image/ukulele/ukulele2.jpg',
    slider3: '../../assets/image/ukulele/ukulele3.jpg',
  },
];
